### ISSUE TITLE
Possible deadlock

### ISSUE THREAD

**Issue by ingjieye** [1lann/go-sip#3]
At udpJanitor() function. 
The thread hold l.udpPoolMutex.Lock(). then check udpPoll for whether there is a UDP connection got timed out. 
If there is, the thread call conn.Close() to close the connection. 
https://github.com/1lann/go-sip/blob/68e86c65407ef8cf672ae38526e7f3d29944b94f/sipnet/connection_pool.go#L81-L85

However, at conn.Close() 
https://github.com/1lann/go-sip/blob/68e86c65407ef8cf672ae38526e7f3d29944b94f/sipnet/connection.go#L198-L216
if c.Listener != nil . This function will try to hold l.udpPoolMutex too.

This cause a deadlock and the program will stop listening for new connections.
Tested on go version go1.12.7 linux/amd64.

I'd like to create a pull request however I'm not familiar with Golang. So any help would be much appreciate. Thanks

**Comment by ingjieye** [comment]
I've checked the caller of Conn.Close() function. The only caller when c.Transport == "udp" is udpJanitor() function. So I've commend out connection.go line 207 and line 209. Works great so far.

**Comment by 1lann** [comment]
Thanks for reporting this, I did a proper fix which is by marking the connections to be closed, and then closing them after the mutex is unlocked.
